// <auto-generated />
using ApiTester.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTester.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250211082405_AddNewSkillsAndInfoTable")]
    partial class AddNewSkillsAndInfoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTester.Models.AccordionModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Data");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApiTester.Models.KeyValuePairModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InfoData");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ApiTester.Models.Education", b =>
                {
                    b.HasBaseType("ApiTester.Models.AccordionModel");

                    b.ToTable("Education", (string)null);
                });

            modelBuilder.Entity("ApiTester.Models.Experience", b =>
                {
                    b.HasBaseType("ApiTester.Models.AccordionModel");

                    b.ToTable("Experience", (string)null);
                });

            modelBuilder.Entity("ApiTester.Models.Info", b =>
                {
                    b.HasBaseType("ApiTester.Models.KeyValuePairModel");

                    b.ToTable("Info", (string)null);
                });

            modelBuilder.Entity("ApiTester.Models.Skills", b =>
                {
                    b.HasBaseType("ApiTester.Models.KeyValuePairModel");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("ApiTester.Models.Education", b =>
                {
                    b.HasOne("ApiTester.Models.AccordionModel", null)
                        .WithOne()
                        .HasForeignKey("ApiTester.Models.Education", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTester.Models.Experience", b =>
                {
                    b.HasOne("ApiTester.Models.AccordionModel", null)
                        .WithOne()
                        .HasForeignKey("ApiTester.Models.Experience", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTester.Models.Info", b =>
                {
                    b.HasOne("ApiTester.Models.KeyValuePairModel", null)
                        .WithOne()
                        .HasForeignKey("ApiTester.Models.Info", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiTester.Models.Skills", b =>
                {
                    b.HasOne("ApiTester.Models.KeyValuePairModel", null)
                        .WithOne()
                        .HasForeignKey("ApiTester.Models.Skills", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
